In [40]:
import numpy as np

def lu_decomposition(A):
    n = len(A)
    L = np.eye(n)  # Initialize L as an identity matrix
    U = np.array(A, dtype=float)  # Copy of A to avoid
    # modifying the original matrix
        # modifying the original matrix
    
    for i in range(n):
        # Eliminate elements below the pivot (U[i, i])
        for j in range(i+1, n):
            if U[i, i] == 0:
                raise ValueError("Zero pivot encountered. LU decomposition cannot proceed.")
            factor = U[j, i] / U[i, i]  # Multiplier for row
                # operation
            L[j, i] = factor  # Store multiplier in L
                # Update the rows of U
            for k in range(i, n):
                U[j, k] -= factor * U[i, k]
    
    return L, U

In [41]:
#Example Code
C= ([[2,3,1],
[4,7,-1],
[-2,1,2]])
L,U = lu_decomposition (C)
print ("Matrix:\n",C)
print ("Lower Matrix L:\n", L)
print ("Upper Matrix U:\n", U)#FIX LU DECOMP THROWN IN AN ARRAY

Matrix:
 [[2, 3, 1], [4, 7, -1], [-2, 1, 2]]
Lower Matrix L:
 [[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1.  4.  1.]]
Upper Matrix U:
 [[ 2.  3.  1.]
 [ 0.  1. -3.]
 [ 0.  0. 15.]]


In [47]:
#Messing around with the matrix
A= [[10,8,3,4],
[9,13,7,11],
[14,6,2,19],
[18,29,3,4]]
L,U =lu_decomposition (A)
print ("Matrix:\n", A)
print ("Matrix:\n", L)
print ("Matrix:\n", U)

Matrix:
 [[10, 8, 3, 4], [9, 13, 7, 11], [14, 6, 2, 19], [18, 29, 3, 4]]
Matrix:
 [[ 1.          0.          0.          0.        ]
 [ 0.9         1.          0.          0.        ]
 [ 1.4        -0.89655172  1.          0.        ]
 [ 1.8         2.51724138 -7.98958333  1.        ]]
Matrix:
 [[ 10.           8.           3.           4.        ]
 [  0.           5.8          4.3          7.4       ]
 [  0.           0.           1.65517241  20.03448276]
 [  0.           0.           0.         138.23958333]]


In [49]:
#Randomized Matrix
M = np.random.randint(1, 21, size=(4, 4))
L, U= lu_decomposition (M)
print ("Matrix:\n", M)
print ("Matrix:\n", L)
print ("Matrix:\n", U)

Matrix:
 [[ 8 10  4 20]
 [ 2 18  4  9]
 [ 6  6 16  1]
 [ 3  8  3 19]]
Matrix:
 [[ 1.          0.          0.          0.        ]
 [ 0.25        1.          0.          0.        ]
 [ 0.75       -0.09677419  1.          0.        ]
 [ 0.375       0.27419355  0.05097087  1.        ]]
Matrix:
 [[  8.          10.           4.          20.        ]
 [  0.          15.5          3.           4.        ]
 [  0.           0.          13.29032258 -13.61290323]
 [  0.           0.           0.          11.09708738]]


In [50]:
import numpy as np
def gaussian_elimination(A, b):
    n = len(b)
# Forward elimination
    for i in range(n):
# Pivoting
        max_row = max(range(i, n), key=lambda x: abs(A[x][i]))
        A[i], A[max_row] = A[max_row], A[i]
        b[i], b[max_row] = b[max_row], b[i]
# Make the rows below this one 0 in current column
        for j in range(i + 1, n):
            ratio = A[j][i] / A[i][i]
            A[j] = [A[j][k] - ratio * A[i][k] for k in range(n)]
            b[j] -= ratio * b[i]
# Backward substitution
    x = [0] * n
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - sum(A[i][j] * x[j] for j in range(i + 1, n))) / A[i][i]
    return x

#Example Code
A= [[3,2,-4],
[2,3,3],
[5,-3,1]]
b=[3,15,14]
solution= gaussian_elimination (A,b)
print ("Gaussian Calculation:", solution)

Gaussian Calculation: [2.9999999999999996, 0.9999999999999996, 2.0]


In [45]:
#Messing around with code
Z= [[10,7,-5],
[18, 9, 9],
[-10, 6, 16]]
x= [17, 9, 14]
solution2= gaussian_elimination(Z,x)
print ("Gaussian Calculation for Practice Code:", solution2)

Gaussian Calculation for Practice Code: [-0.6447368421052633, 2.9078947368421053, -0.6184210526315789]


In [37]:
#Randomization Code
matrix= np.random.rand (5,5)
y= np.random.rand (1,3)
solution3= gaussian_elimination (matrix,y)
print ("Matrix:\n", matrix)
print ("N row:\n", y)
print ("Gaussian Calculation for Randomized:", solution3)

Matrix:
 [[0.57837455 0.86043442 0.87477449 0.1952667  0.17104215]
 [0.75700655 0.48125574 0.95302223 0.93418309 0.6402156 ]
 [0.8835235  0.12086088 0.72888182 0.06789454 0.27402212]
 [0.36088274 0.27453315 0.13723623 0.50182885 0.51404491]
 [0.73878311 0.20476298 0.36388269 0.13397873 0.04044103]]
N row:
 [[0.68609694 0.40128257 0.71653758]]
Gaussian Calculation for Randomized: [array([1.18625022, 0.69381091, 1.23888159])]
