In [1]:
import numpy as np

In [2]:
#function to check if its diagonally dominant
#add up all the row in the function
#compare it to the value thats equal to the row and column
#if the value thats equal to the row and columns its in it will continue
#if the value is not greater than or equal to the row then it will iterate the matrix isn't diagonally dominant
def diagonal_dominance (A):

    rows, cols= A.shape

    for i in range (rows):
        if abs(A[i][i])< sum(abs(A[i][j]) for j in range (cols) if j!= i):
            return False
    
    return True

In [3]:
A= np.array([[0.582745, 0.48 , 0.10 , 0.  , 0.  ],
[0.48 , 1.044129, 0.46 , 0.10 , 0.  ],
[0.10 , 0.46 , 1.10431 , 0.44 , 0.10 ],
[0.  , 0.10 , 0.44 , 0.963889, 0.42 ],
[0.  , 0.  , 0.10 , 0.42 , 0.522565]], dtype=float)
B= np.array([[1, 1], [1, 1.0001]])
C= np.array([[1, 1], [1, 1.0001]])


In [4]:
MatrixA= diagonal_dominance(A)
print ("Matrix A:\n", A)
print ("Is the Matrix Diagonally Dominant?", diagonal_dominance(A))


Matrix A:
 [[0.582745 0.48     0.1      0.       0.      ]
 [0.48     1.044129 0.46     0.1      0.      ]
 [0.1      0.46     1.10431  0.44     0.1     ]
 [0.       0.1      0.44     0.963889 0.42    ]
 [0.       0.       0.1      0.42     0.522565]]
Is the Matrix Diagonally Dominant? True


In [5]:
MatrixB= diagonal_dominance(B)
print ("Matrix B:\n", B)
print ("Is the Matrix Diagonally Dominant?", diagonal_dominance(B))


Matrix B:
 [[1.     1.    ]
 [1.     1.0001]]
Is the Matrix Diagonally Dominant? True


In [6]:
MatrixC= diagonal_dominance(C)
print ("Matrix C:\n", C)
print ("Is the Matrix Diagonally Dominant?", diagonal_dominance(C))

Matrix C:
 [[1.     1.    ]
 [1.     1.0001]]
Is the Matrix Diagonally Dominant? True


In [7]:
D= np.random.rand(3,3)
MatrixD= diagonal_dominance(D)
print ("Matrix D:\n", D)
print ("Is the Matrix Diagonally Dominant?", diagonal_dominance(D))

Matrix D:
 [[0.2965063  0.9541924  0.43163841]
 [0.61312377 0.44357634 0.98819935]
 [0.57698326 0.14059302 0.98166967]]
Is the Matrix Diagonally Dominant? False
