In [2]:
import numpy as np

In [4]:
v1= np.array ([1,2,3])
v2= np.array ([4,5,6])

In [5]:
print (v1)

[1 2 3]


In [6]:
print (v2)

[4 5 6]


In [8]:
v_add= v1+v2
v_sub= v1-v2

In [9]:
print(v_add)

[5 7 9]


In [10]:
print (v_sub)

[-3 -3 -3]


In [11]:
v_scalar= 3*v1

In [12]:
print(v_scalar)

[3 6 9]


In [13]:
v_mult= v1*v2

In [14]:
print (v_mult)

[ 4 10 18]


In [15]:
np.dot (v1,v2)

32

In [16]:
magnitude= np.linalg.norm(v1)

In [17]:
print (magnitude)

3.7416573867739413


In [24]:
A= np.array ([[1,2,3,],[4,5,6]])
print (A)
print()

B= np.array ([[7,8,9], [10,11,12]])
print (B)

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]


In [25]:
matrix_add= A+B
matrix_sub= A-B
print (matrix_add)

[[ 8 10 12]
 [14 16 18]]


In [26]:
transpose= B.T
print (transpose)

[[ 7 10]
 [ 8 11]
 [ 9 12]]


In [27]:
A= np.array ([[2,1],[1,2]])
e_value, e_vector= np.linalg.eig(A)
print (e_value)
print (e_vector)

[3. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [29]:
A= np.array([[4,7],[2,6]])
A_inv=np.linalg.inv(A)
print(A)
print (A_inv)

[[4 7]
 [2 6]]
[[ 0.6 -0.7]
 [-0.2  0.4]]


In [30]:
identity= np.dot(A, A_inv)
print (identity)

[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]
